# Tensor Manipulation

- reshaping
- slicing
- joining or splitting
- transposing and permuting dimension

In [1]:
import torch

In [5]:
# reshaping tensors
# reshape
# view

original_tensor = torch.arange(12)
print(original_tensor)
print(original_tensor.nelement())
print(original_tensor.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
12
1


In [7]:
# 2x6--> 12

reshaped_tensor = original_tensor.reshape(2,6)
print(reshaped_tensor)
print(reshaped_tensor.ndim)
print(reshaped_tensor.nelement())

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
2
12


In [8]:
reshaped_tensor = original_tensor.reshape(3,4)
print(reshaped_tensor)
print(reshaped_tensor.ndim)
print(reshaped_tensor.nelement())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
2
12


In [ ]:
# Performance: Some PyTorch operations, especially those that interact directly with low-level memory (like certain CUDNN operations), expect contiguous tensors for optimal performance.
# Compatibility: Certain functions or modules might require contiguous inputs to work correctly. If you encounter errors related to non-contiguous tensors, using contiguous() can resolve them.
# View Operations: Operations like view() can only be applied to contiguous tensors. If you try to call view() on a non-contiguous tensor, you'll get an error, and you'll need to call .contiguous() first.

In [10]:
# view
print(original_tensor.is_contiguous())
flattened_tensor = original_tensor.view(-1)
print(flattened_tensor)

True
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


## Slicing
Extract specific portions of tensors

In [11]:
tensor_a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor_a)
print(tensor_a.ndim)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2


In [12]:
print(tensor_a[0])

tensor([1, 2, 3])


In [15]:
tensor_a[:,2]

tensor([3, 6, 9])

In [16]:
print(tensor_a.shape)

torch.Size([3, 3])


In [18]:
sub_tensor = tensor_a[1:,1:]
print(sub_tensor.shape)
print(sub_tensor)

torch.Size([2, 2])
tensor([[5, 6],
        [8, 9]])


## Joining tensors

In [2]:
# jis bracket/dimension ko concat krenge uske andr elements bdhege

In [ ]:
# torch.cat() --> merges tensors along an exisiting dimesion.
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5,6],[7,8]])

print(tensor1)
print(tensor2)

print("="*20)

concat_tensor_rows = torch.cat((tensor1, tensor2), dim=0)
concat_tensor_colm = torch.cat((tensor1, tensor2), dim=1)

print(concat_tensor_rows)
print(concat_tensor_colm)
# Possible range is dim range
# In the same dimnsion clubs the element or increases the number of elements

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6],
        [7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [ ]:
# stack --> created a new dimension, increases the tensor's rank
#  both  tensor dimension must match
# jis dim ko stack krenge uske andr same indexes club hongi
print(tensor1.shape)
print(tensor2.shape)

print("="*20)
stack_tensor_rows = torch.stack((tensor1, tensor2), dim=0)
stack_tensor_colm = torch.stack((tensor1, tensor2), dim=1)

print(stack_tensor_rows.shape)
print(stack_tensor_colm.shape)

print(stack_tensor_rows)
print(stack_tensor_colm)


torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([2, 2, 2])
torch.Size([2, 2, 2])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [ ]:
stack_tensor_new = torch.stack((tensor1, tensor2), dim=2)
# This works along the scalars means inside the last bracket
# Stack d0*d1*d2
# Possiblities dim=0 to 3
# dim=x
# no of tensors stack (should have same shape)=n
# new shape=d0*n*x*(x+1)...

## Splitting tensors
- torch.chunk() --> divides your tensor into equal-sized chunks
- torch.split() --> allows uneven splitting based on size

In [ ]:
# torch.chunk
# This function may return fewer than the specified number of chunks!

origin_tensor = torch.arange(12)
# split into a number of chunks who divides the the number of elements in that dimension
chunks = torch.chunk(origin_tensor, 5, dim=0)

print(chunks)

for chunk in chunks:
  print(chunk)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]))
tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])
tensor([ 9, 10, 11])


In [ ]:
# torch.split

splits = torch.split(origin_tensor, 5, dim=0)
# Last chunk will be smaller if the tensor size along the given dimension dim is not divisible by split_size.
print(splits)

for split in splits:
  print(split)

(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9]), tensor([10, 11]))
tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])
tensor([10, 11])


# Transposing and premuting

- transpose() -->swaps two dimesnion. mxn --> nxm
- premute() --> rearranges all dimension in the specified order

In [46]:
# transpose

tensor_original = torch.arange(24).reshape(12,2)

transposed_tensor = tensor_original.transpose(0,1)

print(tensor_original)

print(tensor_original.shape)
print(transposed_tensor.shape)

print(transposed_tensor)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])
torch.Size([12, 2])
torch.Size([2, 12])
tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])


In [1]:
tensor_original = torch.arange(24).reshape(2,3,4)

print(2*3*4)

print(tensor_original.shape)
print(tensor_original)

# [0,1,2]
permuted_tensor = tensor_original.permute(2, 0, 1)
print(permuted_tensor)
print(permuted_tensor.shape)

NameError: name 'torch' is not defined

In [ ]:
l = [4,0,1,2,3,0]

# Cloning and detaching

In [55]:
import copy

a = [1,2,3]
b = copy.deepcopy(a)

print(a)
print(b)

[1, 2, 3]
[1, 2, 3]


In [56]:
tensor = torch.ones(3,3, requires_grad=True) # part of computation graph

cloned_tensor = tensor.clone() # # part of computation graph

detached_tensor = tensor.detach() # this code will detach the tensor from the computation graph
# # non a part of computation graph
# but storage will be same as the original ones

In [ ]:
# | Tensor            | Tracks Gradients? | Part of Computation Graph? | Shares storage with original? |
# | ----------------- | ----------------- | -------------------------- | ----------------------------- |
# | `tensor`          | ✅ Yes             | ✅ Yes                      | Original                      |
# | `cloned_tensor`   | ✅ Yes             | ✅ Yes                      | ❌ No (new memory)             |
# | `detached_tensor` | ❌ No              | ❌ No                       | ✅ Yes (same memory)           |


In [ ]:
# ✅ What is a Computation Graph (in PyTorch and Deep Learning)?
# A computation graph is like a dynamic map of all tensor operations performed on tensors that have requires_grad=True.

# It tracks what operations happened, on which tensors, and in what order, so that during backpropagation, PyTorch knows how to compute gradients automatically.

# ✅ Visual Example:
# For this simple code:

# python
# Copy
# Edit
# import torch

# x = torch.tensor(2.0, requires_grad=True)
# y = x * 3
# z = y ** 2
# PyTorch internally builds this computation graph:

# scss
# Copy
# Edit
# x --(multiply by 3)--> y --(square)--> z
# So when you do:

# python
# Copy
# Edit
# z.backward()
# PyTorch walks backwards along this graph, calculates:

# ∂
# 𝑧
# ∂
# 𝑥
# ∂x
# ∂z
# ​
 
# ✅ Key Properties of Computation Graph:
# Property	Explanation
# Dynamic in PyTorch	The graph is created at runtime (eager execution). Not static like TensorFlow 1.x
# Nodes	Each tensor and operation is a node
# Edges	Each operation applied is an edge connecting tensors
# Direction	It flows forward during computation, and backward during .backward() call
# Autograd system	PyTorch automatically handles graph creation and gradient calculation

# ✅ Why does PyTorch need this graph?
# So that it can apply chain rule of calculus (backpropagation) and compute gradients automatically for each parameter you want to optimize (like weights in neural nets).

# ✅ How Tensors relate to the graph:
# Tensor	Part of Graph?
# Created with requires_grad=True	✅ YES
# Any tensor resulting from ops on it	✅ YES (until detached)
# Detached tensors	❌ Not part of graph

# ✅ Simple working example:
# python
# Copy
# Edit
# x = torch.tensor(2.0, requires_grad=True)
# y = x * 3
# z = y ** 2

# z.backward()

# print(x.grad)   # Should print 12.0
# Why?

# Because:

# bash
# Copy
# Edit
# y = 3x → dy/dx = 3
# z = y^2 → dz/dy = 2y = 2*6=12
# dz/dx = dz/dy * dy/dx = 12
# ✅ Real-life analogy:
# Think of the computation graph like a "history recorder" of your tensor calculations, so PyTorch knows "how you got this result", and can "reverse engineer" gradients when training.

# If you want, I can show how detaching breaks the graph in this example. Want me to?








# You said:
# why they are required


# ChatGPT said:
# ✅ Why Computation Graphs are Required (In Deep Learning / PyTorch)?
# 🎯 Main Reason: Automatic Gradient Calculation (Autograd)
# Deep learning training is all about minimizing a loss function using gradient-based optimization algorithms like SGD, Adam, etc.

# To do that, you need to compute gradients of the loss with respect to each model parameter (weights, biases, etc).

# ✅ The Chain Rule Problem:
# For even a small neural network:

# css
# Copy
# Edit
# Input → Linear → ReLU → Linear → Sigmoid → Loss
# The math behind gradient calculation involves multiple nested chain rule steps, like:

# ∂
# 𝐿
# ∂
# 𝑤
# ∂w
# ∂L
# ​
 
# Where L = Loss, and w = any weight.

# Manually writing these gradients for every layer, activation, etc., is:

# ❌ Time-consuming

# ❌ Error-prone

# ❌ Unscalable (imagine 100-layer networks)

# ✅ Computation Graph Solves This:
# PyTorch automatically builds the graph of operations during forward pass.

# So during .backward():

# PyTorch traverses the graph backward

# Applies chain rule automatically

# Calculates gradients for all tensors that require gradients

# ✅ Example Workflow:
# Phase	What happens
# Forward Pass	PyTorch records the operations and builds the computation graph
# Loss Calculation	Output → Loss
# Backward Pass	.backward() triggers graph traversal for gradient computation
# Optimizer Step	Gradients are used by optimizer to update weights

# ✅ Without Computation Graph:
# You'd have to manually calculate derivatives for each operation, like:

# For a simple function:

# python
# Copy
# Edit
# f(x) = (x * 3) ^ 2
# You'd have to manually write:

# 𝑑
# 𝑓
# 𝑑
# 𝑥
# =
# 2
# ×
# (
# 3
# 𝑥
# )
# ×
# 3
# =
# 18
# 𝑥
# dx
# df
# ​
#  =2×(3x)×3=18x
# Imagine doing this for big neural nets… Impossible at scale.

# ✅ Benefits of Computation Graphs:
# Benefit	Explanation
# No manual gradient calculation	PyTorch does it
# Works for any arbitrary operation	Even your custom functions
# Supports dynamic graphs	PyTorch graphs are built at runtime (eager execution)
# Memory-efficient	PyTorch stores just enough history to compute gradients

# ✅ Quick Recap:
# Computation graphs are required because they enable automatic differentiation, which is fundamental for training neural networks using backpropagation.